---
  - name: Config Web VM with Docker
    hosts: elk
    remote_user: ptadmin
    become: True
    tasks:

    - name: Install Docker.io
      apt:
       update_cache: yes
       force_apt_get: yes
       name: docker.io
       state: present

    - name: Install PIP
      apt:
       force_apt_get: yes
       name: python3-pip
       state: present

    - name: Install Docker python module
      pip:
       name: docker
       state: present

    - name: Increase vm memory on elkVM
      command: sysctl -w vm.max_map_count=262144

    - name: Increase vm memory on restart
      shell: echo "vm.max_map_count=262144" >> /etc/sysctl.conf

    - name: Use more memory
      ansible.posix.sysctl:
       name: vm.max_map_count
       value: "262144"
       state: present
       reload: yes

    - name: Download and launch docker elk
      docker_container:
       name: elk
       image: sebp/elk:761
       state: started
       restart_policy: always
       ports:
         - "5601:5601"
         - "9200:9200"
         - "5044:5044"

    - name: Enable Docker on Boot
      systemd:
       name: docker
       enabled: yes
